### ISSUE TITLE
Cards Delayed for Longer than they should be

### ISSUE THREAD

**Issue by BaekToDaFuture** [is343/anki_delay_deck#1]
Hello,

Before I start I would like to state that I am currently using a few add-ons of which I'm pretty sure that doesn't alter any scheduling, but I AM using add-on [Load balanced scheduler](https://ankiweb.net/shared/info/208879074).

I tried to use the add-on after a day of delay, yet they seem to get delayed for an unforeseeable amount of time. Some decks were delayed for 98 days for example, some were for 58 days.

 It could just be my cards however, since I do know that my database could be slightly corrupt (I did run database checks via native Anki database check) due to a few add-ons that altered the scheduling in the past.

Thank you.

**Comment by is343** [comment]
@BaekToDaFuture
I'm sorry for the late reply. My notifications were not set correctly for this repo. 
Sorry to hear that, were you able to recover from a previous backup?

None of the decks were delayed by the correct number of days? That is, were all of the decks you tried it with incorrect?

Can you confirm that the decks delay differently if the load balancer add-on is disabled?

Were your decks all up to date up until that point? This add-on will delay all of the cards based on the MOST overdue card. So for example, if one card was overdue by 60 days but the rest by 3 days, they would all be delayed by 60 days.

I might try adding a text input to allow for delaying cards a user defined number of days.

**Comment by is343** [comment]
This was probably an issue with a suspended card that had a due date attached to it. I have now excluded suspended cards from the calculations.

**Comment by is343** [comment]
Probable cause fixed in #2
