### ISSUE TITLE
Delay Overdue not working on select decks

### ISSUE THREAD

**Issue by maevjs** [is343/anki_delay_deck#5]
This is a similar issue as to what was previously posted that was resolved with the nested decks update. When I tried using the add-on on an old deck with many Overdue Days, it worked as intended. However, when I attempt it on two nested decks that I skipped for a day (to try it out), it tells me that there are "0" Overdue Days; when I input "1", a pop-up claims that a 1-day delay was processed, but nothing changes (number of reviews remains the same). Is this a bug or am I using this incorrectly?

**Comment by is343** [comment]
Hi sorry for the super late response, I must have missed this issue. Can you give me some detail about how your deck is organized?

**Comment by maevjs** [comment]
The addon ended up working just fine after that one day, probably because it was a newer deck.

Best,

Ryan
