### ISSUE TITLE
Does this work on anki version 2.1.49? Should I be safe to try?

### ISSUE THREAD

**Issue by JNajjar1** [is343/anki_delay_deck#6]
I currently use Miagku, an add-on with similar purposes to delay overdue. But Migaku only works on Anki 2.1.35. I will switch to Delay Overdue Cards if I can do so on 2.1.49.

**Comment by is343** [comment]
Hi, this should be working still. I just tried `2.1.49` and `2.1.54` on mac and it seems to be working for me.

You can safely test by syncing your deck with ankiweb. You can force push your decks to the cloud by going into the settings and going to the `Network` tab and checking the `On next sync, force changes in one direction` option.

Then click they sync / refresh button in the main screen. The popup will ask if you want to download from ankiweb, or upload to ankiweb.

Choose upload to send your current local deck to the cloud.

Then you can test it out locally. If something breaks or doesn't work for you, then just check the box again to force a one direction sync. This time choose to download your deck from the cloud.
