### ISSUE TITLE
Anki delay overdue cards - cards are sometimes showing earlier than the set learning interval

### ISSUE THREAD

**Issue by JinDotCom** [is343/anki_delay_deck#9]
Hi, so for example I set the interval to this card in 13 days on the 10th of Jan, but the due date has been set to the 13th of Jan. Other cards are being shown earlier than the supposed due date. 

<img width="759" alt="image" src="https://github.com/is343/anki_delay_deck/assets/96188708/1b25ecbd-e419-4872-bf9e-5766a087dd34">

The interval is set to 13days but it showed up 3 days later.

I updated Anki to Version 23.12.1 a few days ago and that's when I started having this problem

**Comment by is343** [comment]
Hello!
Thanks for bringing this to my attention. I haven't touched this plugin for some time, so I would not be surprised if something might have broken after some major update.

So, to confirm that this was working fine for you before you updated?

To be on the safe side, I would recommend not using this again on your current Anki version. I have no idea what might be going on.

I'll try taking a look at what the problem might be sometime this weekend. Hopefully I've have an answer for you in a few days.

**Comment by JinDotCom** [comment]
> Hello! Thanks for bringing this to my attention. I haven't touched this plugin for some time, so I would not be surprised if something might have broken after some major update.
> 
> So, to confirm that this was working fine for you before you updated?
> 
> To be on the safe side, I would recommend not using this again on your current Anki version. I have no idea what might be going on.
> 
> I'll try taking a look at what the problem might be sometime this weekend. Hopefully I've have an answer for you in a few days.

Thanks, now to be honest I'm not sure if it was working fine in the previous version(the version before the update was ⁨2.1.62). I wasn't able to check the said card for a couple of months because I had some other materials that needed attending to and during then, all I could do was delay it. 

But just to summarise the problems:
1) Some of the cards (like the one above) are showing up earlier than the scheduled date. 
- The one above was scheduled to show after 13 days on Jan 10th, but it showed up 3 days later

2) The "Interval" at the top of the info and the most recent "Interval" in the table don't seem to match.
- You can see that the "Interval" at the top shows 9 days but the "Interval" in the table is set for 13days

Just to be safe, I downgraded my Anki to 2.1.62. 

Let me know if anything comes up. Cheers

**Comment by is343** [comment]
Hey, just wanted to drop in to let you know that I'm still looking into this.
It turns out that there were indeed breaking changes from 2.1.x -> 23.10. They have [a post](https://forums.ankiweb.net/t/porting-tips-for-anki-23-10/35916) regarding porting plugins to get them working.

Soooo this does seem like a known thing so that's good - we know what's wrong.
Bad news is that this is a bit of a todo and I was hoping to get more done over the long weekend, butttt I didn't have time to sit down and hammer this out.

I'll try to plink away at this in my free time throughout this week / next weekend.

I will definitely let you know once it's updated.

**Comment by JinDotCom** [comment]
Cheers, in the meantime I guess I'll jsut stick with 2.1x

**Comment by is343** [comment]
@JinDotCom Hi, sorry again for the delay.
I think I've got it working for me locally. I uploaded a new version of the addon that uses the updated code for version 23+

If you want to try updating anki, then also updating the addon, you can try again.

If you do, please let me know either way if it works or if there is any issue.
